//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedSpartan.BrimstoneCompanion.AppLayer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TextResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RedSpartan.BrimstoneCompanion.AppLayer.Resources.TextResource", typeof(TextResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agility.
        /// </summary>
        internal static string AGI {
            get {
                return ResourceManager.GetString("AGI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combat.
        /// </summary>
        internal static string CBT {
            get {
                return ResourceManager.GetString("CBT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cunning.
        /// </summary>
        internal static string CNG {
            get {
                return ResourceManager.GetString("CNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corruption.
        /// </summary>
        internal static string CPT {
            get {
                return ResourceManager.GetString("CPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defence.
        /// </summary>
        internal static string DEF {
            get {
                return ResourceManager.GetString("DEF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Stone.
        /// </summary>
        internal static string DKS {
            get {
                return ResourceManager.GetString("DKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dollars.
        /// </summary>
        internal static string DLR {
            get {
                return ResourceManager.GetString("DLR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experience.
        /// </summary>
        internal static string EXP {
            get {
                return ResourceManager.GetString("EXP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grit.
        /// </summary>
        internal static string GRT {
            get {
                return ResourceManager.GetString("GRT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health.
        /// </summary>
        internal static string HLT {
            get {
                return ResourceManager.GetString("HLT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horror.
        /// </summary>
        internal static string HRR {
            get {
                return ResourceManager.GetString("HRR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heavy.
        /// </summary>
        internal static string HVY {
            get {
                return ResourceManager.GetString("HVY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initiative.
        /// </summary>
        internal static string INT {
            get {
                return ResourceManager.GetString("INT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lore.
        /// </summary>
        internal static string LOR {
            get {
                return ResourceManager.GetString("LOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luck.
        /// </summary>
        internal static string LUK {
            get {
                return ResourceManager.GetString("LUK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Melee.
        /// </summary>
        internal static string MLE {
            get {
                return ResourceManager.GetString("MLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranged.
        /// </summary>
        internal static string RNG {
            get {
                return ResourceManager.GetString("RNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sanity.
        /// </summary>
        internal static string SAN {
            get {
                return ResourceManager.GetString("SAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spirit.
        /// </summary>
        internal static string SPT {
            get {
                return ResourceManager.GetString("SPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strength.
        /// </summary>
        internal static string STR {
            get {
                return ResourceManager.GetString("STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Willpower.
        /// </summary>
        internal static string WIL {
            get {
                return ResourceManager.GetString("WIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wounds.
        /// </summary>
        internal static string WND {
            get {
                return ResourceManager.GetString("WND", resourceCulture);
            }
        }
    }
}
